name: vla-wm
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - h5py
  - pyyaml
  - tqdm
  - matplotlib
  - opencv
  - imageio
  - imageio-ffmpeg
  - pytorch
  - pytorch-cuda=12.1
  - torchvision
  - torchaudio
  - pip:
      - robomimic==0.3.0
      - tensorboard
      - timm
      - transformers
      - accelerate
